### ISSUE TITLE
Lists of URLs contain duplicates

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/dashboard#16]
e.g. LIFESTAGE Third Age 
https://discovery.closer.ac.uk/item/uk.cls.ncds/f36fceca-f815-49ad-a4bd-efaeac29cac5
https://discovery.closer.ac.uk/item/uk.lha/463f5929-f5b1-4591-90d7-a57fa84a43cf
https://discovery.closer.ac.uk/item/uk.cls.ncds/f36fceca-f815-49ad-a4bd-efaeac29cac5
https://discovery.closer.ac.uk/item/uk.lha/463f5929-f5b1-4591-90d7-a57fa84a43cf
https://discovery.closer.ac.uk/item/uk.cls.ncds/f36fceca-f815-49ad-a4bd-efaeac29cac5

JJ suggested this might relate to the different versions. Can we include the version number please?

**Comment by ollylucl** [comment]
As somone pointed out before the issue is that an API query on clsr-ppcolw01n.addev.ucl.ac.uk is returning multiple studyunit versions (this error doesn't happen when running the same query on discovery.closer.ac.uk however, I guess because the duplicates don't exist there).

I'll create a branch that specifically requests the latest version of studyunit and issue a pull request.

**Comment by ollylucl** [comment]
Resolved in https://github.com/CLOSER-Cohorts/dashboard/pull/17
